name: Create AWS Infrastructure with Terraform

on:
  push:
    branches: [main]
  workflow_dispatch:  # optional: allow manual trigger

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./Eks-terraform

    - name: Terraform Validate (optional)
      run: terraform validate
      working-directory: ./Eks-terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./Eks-terraform
